### ISSUE TITLE
Recommended Flags for Azul Platform Prime

### ISSUE THREAD

**Issue by mucookul** [brucethemoose/Minecraft-Performance-Flags-Benchmarks#49]
I want to run a personal minecraft server with Azul Platform Prime. Are there any recommended flags for it?

**Comment by isenberg** [comment]
For any JVM implementation which differs from OpenJDK I would suggest to begin performance testing without any special -XX flags as most special OpenJDK flags are just ignored by other JVM implementations. When using Azul Platform Prime usually no tuning with special flags is necessary. For highest performance check out the following Linux system settings explained on the first two links:

https://docs.azul.com/prime/installation-and-configuration
https://docs.azul.com/prime/Enable-Huge-Pages
https://docs.azul.com/prime/Heap-Size

**Comment by mucookul** [comment]
Thanks! This helped a lot, testing with graalvm and platform prime.

**Comment by mucookul** [comment]
Just saying, seems like GraalVM is way faster than Azul Platform Prime
(haven't tested many flags though)
I didn't run the benchmark, just did quick tests on my server

**Comment by isenberg** [comment]
> seems like GraalVM is way faster than Azul Platform Prime

Is the benchmark in its current default configuration matching scenarios a real game server in public or commercial setup will face? With a small modification to make the test more realistic I can't confirm above observation and both JVMs are quite similar in performance in the test I ran. Or do you have situations in real scenarios where you restart the process every few seconds?

I installed the benchmark on an Ubuntu x86_64 system and ran the server-benchmark with some modifications to make it more real-world relevant in my understanding. Because with the default setting in Benchmark.py the actual test duration of the performance-critical game-functions was only about 10 seconds for each java process start and each test iteration stopped and started the java process while public or commercial game servers most likely ran for a few hours to days before being restarted.

To achieve that I modified Benchmark.py as follows:

Using the lightmemory setting in the blist section for the server benchmarks (-Xmx4G).
Set iterations to 1 in blist.

Then changing the following lines in Benchmark.py with lines marked with - being removed and lines with + added. For the small test system I ran I reduced the number of spawned players, if you have a larger system you can keep that of course.

The most important change was adding "chunky radius 1500" which increased the world generation area so that a single test duration now runs about 7 minutes instead of only 10 seconds.

```
-carpet = 67 #number of simulated players if the "Carpet" fabric mod is present
+carpet = 2 #number of simulated players if the "Carpet" fabric mod is present

   g1gc = False
+ chunkdef_command = ""
   chunkgen_command = ""

         if debug: print("Found Fabric: " + f)
+       chunkdef_command = r'''chunky radius 1500'''
         chunkgen_command = fabric_chunkgen_command

           start = time.time()
+         mcserver.sendline(chunkdef_command)   #define chunk size
           mcserver.sendline(chunkgen_command)   #Generate chunks

```

**Comment by mucookul** [comment]
Thanks, I'll merge this into my fork/pull request.
Edit: It seems like no code changes are needed as everything looks correct and I think 67 is fine.

**Comment by isenberg** [comment]
Thanks! Do you also plan to add the change with "chunky radius 1500" to increase the testing duration from 10 seconds to 7 minutes to make it more real-game-like? I can also file a separate new issue for that if preferred.
