### ISSUE TITLE
What were the changes in the redesign?

### ISSUE THREAD

**Issue by HyperSoop** [brucethemoose/Minecraft-Performance-Flags-Benchmarks#8]
This question. I noticed the amount of flags has decreased hugely, does this surely not affect anyhting?

**Comment by HyperSoop** [comment]
Also, why were the Java 8 flags moved down to a spoilered collapsed unreadable code block?

**Comment by brucethemoose** [comment]
So for the redesign, I culled all the flags that are already enabled by default in Java 17, and then split them up into more modular blocks. It looks different... but TBH it will perform almost exactly the same as pre-redesign, even with the G1GC changes.


I felt it was particularly important for OpenJDK users to pick/try their own garbage collector, instead of defaulting to g1gc.


Also, I have focused on testing Java 17 over Java 8 since the initial post, and didnt want to "advertise" it before I at least go through and cull redundant arguments. The block... was a bad idea, lol
